/**
 * 成本管理模块种子数据。
 * 从 useCostManagement.ts 提取的默认静态数据常量，
 * 供 service 层 seedIfEmpty() 在首次使用时自动灌入数据库。
 */
import type { PriceResourceItem } from '@/types/price-library.types'
import type { QuotaItem, ParamRule, QuotaComponent } from '@/types/quota-library.types'

const asphaltMixingComponents: QuotaComponent[] = [
  {
    id: 'tpl-asphalt-mixing',
    category: 'mixing',
    name: '沥青混合料拌合费',
    unit: 't',
    basis: 'tonnage',
    consumption: 1,
    price: 12,
    formula: '按混合料吨耗计入拌合站加工费',
  },
]

const cementStabilizedMixingComponents: QuotaComponent[] = [
  {
    id: 'tpl-csm-mixing',
    category: 'mixing',
    name: '水泥稳定碎石拌合费',
    unit: 't',
    basis: 'tonnage',
    consumption: 1,
    price: 8,
    formula: '按水稳混合料吨耗计入集中拌合费',
  },
]

export const SEED_QUOTA_ITEMS: QuotaItem[] = [
  {
    id: 'LM-AC20C',
    code: 'NB-LM-001',
    name: 'AC-20C 沥青混凝土下面层',
    baseUnit: 'm3',
    defaultThicknessCm: 6,
    density: 2.38,
    lossRate: 2,
    caliber: '定额 m3 基准，清单厚度换算为 m2',
    components: asphaltMixingComponents,
  },
  {
    id: 'LM-AC13C',
    code: 'NB-LM-002',
    name: 'AC-13C 沥青混凝土上面层',
    baseUnit: 'm3',
    defaultThicknessCm: 4,
    density: 2.36,
    lossRate: 2,
    caliber: '定额 m3 基准，清单厚度换算为 m2',
    components: asphaltMixingComponents,
  },
  {
    id: 'LM-SMA13',
    code: 'NB-LM-003',
    name: 'SMA-13 沥青玛蹄脂碎石上面层',
    baseUnit: 'm3',
    defaultThicknessCm: 4,
    density: 2.42,
    lossRate: 2,
    caliber: 'SMA高等级面层，定额 m3 基准，清单厚度换算为 m2',
    components: asphaltMixingComponents,
  },
  {
    id: 'LM-AC25C',
    code: 'NB-LM-004',
    name: 'AC-25C 沥青混凝土下面层',
    baseUnit: 'm3',
    defaultThicknessCm: 8,
    density: 2.40,
    lossRate: 2,
    caliber: '粗粒式下面层，定额 m3 基准，清单厚度换算为 m2',
    components: asphaltMixingComponents,
  },
  {
    id: 'LM-TACK',
    code: 'NB-LM-011',
    name: '乳化沥青粘层油',
    baseUnit: 'm2',
    defaultThicknessCm: 0,
    density: 0,
    lossRate: 3,
    caliber: '油层按 m2 测算，无厚度换算',
    components: [],
  },
  {
    id: 'LM-PRIME',
    code: 'NB-LM-012',
    name: '乳化沥青/煤沥青透层油',
    baseUnit: 'm2',
    defaultThicknessCm: 0,
    density: 0,
    lossRate: 3,
    caliber: '透层按 m2 测算，无厚度换算',
    components: [],
  },
  {
    id: 'LM-MILL-04',
    code: 'NB-LM-021',
    name: '旧沥青路面铣刨',
    baseUnit: 'm2',
    defaultThicknessCm: 4,
    density: 0,
    lossRate: 0,
    caliber: '旧路铣刨按设计厚度直接测算 m2',
    components: [],
  },
  {
    id: 'LM-BASE-CSM',
    code: 'NB-LM-031',
    name: '水泥稳定碎石基层',
    baseUnit: 'm3',
    defaultThicknessCm: 20,
    density: 2.30,
    lossRate: 3,
    caliber: '水稳基层，定额 m3 基准，清单厚度换算为 m2',
    components: cementStabilizedMixingComponents,
  },
]

export const SEED_PARAM_RULES: Record<string, Record<string, ParamRule>> = {
  'LM-AC20C': {
    thicknessCm: { defaultVal: 6.0, minValid: 5.0, maxValid: 10.0, desc: '规范推荐厚度 6~8cm，过薄易开裂，过厚难以压实。', warningMsg: '厚度超出合理范围(5~10cm)！' },
    density: { defaultVal: 2.38, minValid: 2.25, maxValid: 2.45, desc: 'AC-20C 设计压实密度通常在 2.35~2.42 t/m³ 之间。', warningMsg: '密度超出合理设计范围(2.25~2.45 t/m³)！' },
    lossRate: { defaultVal: 2.0, minValid: 1.0, maxValid: 4.0, desc: '路面施工经验损耗率 1.0%~4.0%。', warningMsg: '损耗率异常(合理范围: 1%~4%)！' },
    haulDistanceKm: { defaultVal: 18.0, minValid: 5.0, maxValid: 50.0, desc: '合理成品运输距离 5~50km。过长会导致沥青混合料严重温度离析。', warningMsg: '运距过短或有温度离析风险(5~50km)！' },
    managementRate: { defaultVal: 5.0, minValid: 2.0, maxValid: 10.0, desc: '企业管理费计取率通常为 2.0%~10.0%。', warningMsg: '管理费率超出常规测算标准！' },
    profitRate: { defaultVal: 6.0, minValid: 2.0, maxValid: 12.0, desc: '测算利润计取率通常为 2.0%~12.0%。', warningMsg: '利润率超出常规测算标准！' },
    taxRate: { defaultVal: 9.0, minValid: 3.0, maxValid: 9.0, desc: '建筑业一般计税 VAT 增值税标准为 9%，简易征收为 3%。', warningMsg: '税率不符合标准规范(3% 或 9%)！' },
    laborProductivity: { defaultVal: 108, minValid: 90, maxValid: 130, desc: '规范配合人工工效一般为 90~130 m²/工日。', warningMsg: '人工工效偏离行业规范合理区间(90~130)！' },
    paverProductivity: { defaultVal: 1333, minValid: 1000, maxValid: 1600, desc: '9m摊铺机台班摊铺面积一般为 1000~1600 m²/台班。', warningMsg: '摊铺机工效偏离行业常规合理区间(1000~1600)！' },
    rollerProductivity: { defaultVal: 1258, minValid: 900, maxValid: 1500, desc: '压路机组合联合台班压实面积一般为 900~1500 m²/台班。', warningMsg: '压路机工效偏离行业常规合理区间(900~1500)！' },
    asphaltRatio: { defaultVal: 4.5, minValid: 3.5, maxValid: 6.5, desc: '沥青含量百分比（通常为 3.5%~6.5%）。', warningMsg: '沥青配比超出常规设计范围！' },
    coarseRatio: { defaultVal: 60.0, minValid: 45.0, maxValid: 75.0, desc: '粗集料比例（通常为 45%~75%）。', warningMsg: '粗集料配比超出常规设计范围！' },
    fineRatio: { defaultVal: 32.5, minValid: 20.0, maxValid: 45.0, desc: '细集料比例（通常为 20%~45%）。', warningMsg: '细集料配比超出常规设计范围！' },
    powderRatio: { defaultVal: 3.0, minValid: 1.5, maxValid: 6.0, desc: '矿粉比例（通常为 1.5%~6.0%）。', warningMsg: '矿粉配比超出常规设计范围！' },
  },
  'LM-AC13C': {
    thicknessCm: { defaultVal: 4.0, minValid: 3.0, maxValid: 6.0, desc: '上面层推荐厚度 3~5cm。厚度需与粗骨料最大粒径匹配，太薄易脱落。', warningMsg: '上面层厚度异常(3~6cm)！' },
    density: { defaultVal: 2.36, minValid: 2.25, maxValid: 2.45, desc: 'AC-13C 设计压实密度通常在 2.34~2.42 t/m³ 之间。', warningMsg: '密度超出合理设计范围(2.25~2.45 t/m³)！' },
    lossRate: { defaultVal: 2.0, minValid: 1.0, maxValid: 4.0, desc: '上面层施工经验损耗率 1.0%~4.0%。', warningMsg: '损耗率异常(合理范围: 1%~4%)！' },
    haulDistanceKm: { defaultVal: 18.0, minValid: 5.0, maxValid: 50.0, desc: '成品料合理运距 5~50km。运距过长会导致上面层摊铺温度过低。', warningMsg: '运距过长将导致摊铺离析(5~50km)！' },
    managementRate: { defaultVal: 5.0, minValid: 2.0, maxValid: 10.0, desc: '企业管理费计取率通常为 2.0%~10.0%。', warningMsg: '管理费率超出常规测算标准！' },
    profitRate: { defaultVal: 6.0, minValid: 2.0, maxValid: 12.0, desc: '测算利润计取率通常为 2.0%~12.0%。', warningMsg: '利润率超出常规测算标准！' },
    taxRate: { defaultVal: 9.0, minValid: 3.0, maxValid: 9.0, desc: '增值税标准税率为 9% 或 3%。', warningMsg: '税率不符合标准规范(3% 或 9%)！' },
    laborProductivity: { defaultVal: 108, minValid: 90, maxValid: 130, desc: '规范配合人工工效一般为 90~130 m²/工日。', warningMsg: '人工工效偏离行业规范合理区间(90~130)！' },
    paverProductivity: { defaultVal: 1333, minValid: 1000, maxValid: 1600, desc: '9m摊铺机台班摊铺面积一般为 1000~1600 m²/台班。', warningMsg: '摊铺机工效偏离行业常规合理区间(1000~1600)！' },
    rollerProductivity: { defaultVal: 1258, minValid: 900, maxValid: 1500, desc: '压路机组合联合台班压实面积一般为 900~1500 m²/台班。', warningMsg: '压路机工效偏离行业常规合理区间(900~1500)！' },
    asphaltRatio: { defaultVal: 5.0, minValid: 3.5, maxValid: 6.5, desc: '沥青含量百分比（通常为 3.5%~6.5%）。', warningMsg: '沥青配比超出常规设计范围！' },
    coarseRatio: { defaultVal: 60.0, minValid: 45.0, maxValid: 75.0, desc: '粗集料比例（通常为 45%~75%）。', warningMsg: '粗集料配比异常！' },
    fineRatio: { defaultVal: 32.0, minValid: 20.0, maxValid: 45.0, desc: '细集料比例（通常为 20%~45%）。', warningMsg: '细集料配比异常！' },
    powderRatio: { defaultVal: 3.0, minValid: 1.5, maxValid: 6.0, desc: '矿粉比例（通常为 1.5%~6.0%）。', warningMsg: '矿粉配比异常！' },
  },
  'LM-TACK': {
    lossRate: { defaultVal: 3.0, minValid: 1.0, maxValid: 5.0, desc: '粘层油洒布洒漏损耗率经验值为 1.0%~5.0%。', warningMsg: '洒布损耗率超出常理(1%~5%)！' },
    managementRate: { defaultVal: 3.0, minValid: 1.0, maxValid: 10.0, desc: '通常为 1.0%~10.0%。', warningMsg: '费率偏离常规！' },
    profitRate: { defaultVal: 4.0, minValid: 1.0, maxValid: 12.0, desc: '通常为 1.0%~12.0%。', warningMsg: '费率偏离常规！' },
    taxRate: { defaultVal: 9.0, minValid: 3.0, maxValid: 9.0, desc: '标准税率 9% 或 3%。', warningMsg: '税率异常！' },
    tackApplicationRate: { defaultVal: 0.0012, minValid: 0.0008, maxValid: 0.0018, desc: '粘层油洒布量规范要求通常在 0.0008~0.0018 t/m² (即 0.8~1.8 kg/m²)。', warningMsg: '洒布油量超出规范限制(0.8~1.8 kg/m²)！' },
    sprayProductivity: { defaultVal: 3000, minValid: 2000, maxValid: 4000, desc: '沥青洒布车日均洒布面积经验值为 2000~4000 m²/台班。', warningMsg: '洒布车工效异常(合理范围: 2000~4000)！' },
  },
  'LM-MILL-04': {
    thicknessCm: { defaultVal: 4.0, minValid: 2.0, maxValid: 10.0, desc: '旧路铣刨深度通常在 2.0~10.0 cm 之间。', warningMsg: '单次铣刨深度异常(2~10cm)！' },
    haulDistanceKm: { defaultVal: 5.0, minValid: 1.0, maxValid: 30.0, desc: '铣刨渣土运输弃渣运距通常为 1~30km。', warningMsg: '渣土运距超出合理运输范围(1~30km)！' },
    managementRate: { defaultVal: 5.0, minValid: 2.0, maxValid: 10.0, desc: '管理费率通常为 2.0%~10.0%。', warningMsg: '管理费率超出常规！' },
    profitRate: { defaultVal: 5.0, minValid: 2.0, maxValid: 10.0, desc: '利润率通常为 2.0%~10.0%。', warningMsg: '利润率超出常规！' },
    taxRate: { defaultVal: 9.0, minValid: 3.0, maxValid: 9.0, desc: '标准税率 9% 或 3%。', warningMsg: '税率异常！' },
    millProductivity: { defaultVal: 2000, minValid: 1200, maxValid: 3000, desc: '2m铣刨机台班铣刨面积经验值为 1200~3000 m²/台班。', warningMsg: '铣刨机工效偏离经验区间(1200~3000)！' },
    slagFactor: { defaultVal: 0.100, minValid: 0.050, maxValid: 0.200, desc: '铣刨废料渣土重量系数通常在 0.05~0.2 t/m² 之间（按 2.3t/m³ 松散折算）。', warningMsg: '渣土重量系数异常！' },
  },
  'LM-SMA13': {
    thicknessCm: { defaultVal: 4.0, minValid: 3.5, maxValid: 5.0, desc: '上面层推荐厚度 3.5~5cm。需配合改性沥青与木质素纤维铺筑。', warningMsg: 'SMA-13厚度建议在3.5~5cm区间！' },
    density: { defaultVal: 2.42, minValid: 2.38, maxValid: 2.46, desc: 'SMA-13 设计压实密度通常在 2.38~2.46 t/m³ 之间。', warningMsg: '密度超出合理设计范围！' },
    lossRate: { defaultVal: 2.0, minValid: 1.0, maxValid: 4.0, desc: '施工经验损耗率 1.0%~4.0%。', warningMsg: '损耗率异常(合理范围: 1%~4%)！' },
    haulDistanceKm: { defaultVal: 18.0, minValid: 5.0, maxValid: 50.0, desc: '合理成品运输距离 5~50km。', warningMsg: '运距异常！' },
    managementRate: { defaultVal: 5.0, minValid: 2.0, maxValid: 10.0, desc: '企业管理费计取率通常为 2.0%~10.0%。', warningMsg: '管理费率超出常规！' },
    profitRate: { defaultVal: 6.0, minValid: 2.0, maxValid: 12.0, desc: '测算利润计取率通常为 2.0%~12.0%。', warningMsg: '利润率超出常规！' },
    taxRate: { defaultVal: 9.0, minValid: 3.0, maxValid: 9.0, desc: '建筑业一般计税 VAT 增值税标准为 9%，简易征收为 3%。', warningMsg: '税率不符合规范！' },
    laborProductivity: { defaultVal: 100, minValid: 80, maxValid: 120, desc: 'SMA配合人工工效一般为 80~120 m²/工日（工艺复杂速度稍缓）。', warningMsg: '人工工效偏离合理区间！' },
    paverProductivity: { defaultVal: 1200, minValid: 900, maxValid: 1500, desc: '9m摊铺机台班摊铺面积一般为 900~1500 m²/台班。', warningMsg: '摊铺机工效偏离合理区间！' },
    rollerProductivity: { defaultVal: 1100, minValid: 800, maxValid: 1400, desc: 'SMA压实工效一般为 800~1400 m²/台班（需紧跟慢压、防过度碾压）。', warningMsg: '压路机工效偏离合理区间！' },
    asphaltRatio: { defaultVal: 6.0, minValid: 5.5, maxValid: 6.8, desc: 'SMA改性沥青含量百分比（通常为 5.5%~6.8%）。', warningMsg: '沥青配比超出常规设计范围！' },
    coarseRatio: { defaultVal: 72.0, minValid: 65.0, maxValid: 80.0, desc: '粗集料比例较高（通常为 65%~80%）。', warningMsg: '粗集料配比超出范围！' },
    fineRatio: { defaultVal: 16.0, minValid: 10.0, maxValid: 22.0, desc: '细集料比例较低（通常为 10%~22%）。', warningMsg: '细集料配比超出范围！' },
    powderRatio: { defaultVal: 6.0, minValid: 4.5, maxValid: 8.5, desc: '矿粉比例（通常为 4.5%~8.5%）。', warningMsg: '矿粉配比超出范围！' },
  },
  'LM-AC25C': {
    thicknessCm: { defaultVal: 8.0, minValid: 6.0, maxValid: 12.0, desc: '粗粒式下面层推荐厚度 6~12cm。', warningMsg: '厚度超出合理范围！' },
    density: { defaultVal: 2.40, minValid: 2.30, maxValid: 2.48, desc: 'AC-25C 设计压实密度通常在 2.30~2.48 t/m³ 之间。', warningMsg: '密度超出合理设计范围！' },
    lossRate: { defaultVal: 2.0, minValid: 1.0, maxValid: 4.0, desc: '路面施工经验损耗率 1.0%~4.0%。', warningMsg: '损耗率异常！' },
    haulDistanceKm: { defaultVal: 18.0, minValid: 5.0, maxValid: 50.0, desc: '合理成品运输距离 5~50km。', warningMsg: '运距异常！' },
    managementRate: { defaultVal: 5.0, minValid: 2.0, maxValid: 10.0, desc: '企业管理费计取率通常为 2.0%~10.0%。', warningMsg: '管理费率超出常规！' },
    profitRate: { defaultVal: 6.0, minValid: 2.0, maxValid: 12.0, desc: '测算利润计取率通常为 2.0%~12.0%。', warningMsg: '利润率超出常规！' },
    taxRate: { defaultVal: 9.0, minValid: 3.0, maxValid: 9.0, desc: '增值税标准税率为 9% 或 3%。', warningMsg: '税率不符合规范！' },
    laborProductivity: { defaultVal: 115, minValid: 90, maxValid: 135, desc: '下面层人工工效一般为 90~135 m²/工日。', warningMsg: '人工工效偏离合理区间！' },
    paverProductivity: { defaultVal: 1400, minValid: 1000, maxValid: 1700, desc: '9m摊铺机台班摊铺面积一般为 1000~1700 m²/台班。', warningMsg: '摊铺机工效偏离合理区间！' },
    rollerProductivity: { defaultVal: 1300, minValid: 900, maxValid: 1600, desc: '压路机组合联合台班压实面积一般为 900~1600 m²/台班。', warningMsg: '压路机工效偏离合理区间！' },
    asphaltRatio: { defaultVal: 4.0, minValid: 3.2, maxValid: 5.0, desc: '沥青含量百分比（通常为 3.2%~5.0%）。', warningMsg: '沥青配比超出常规设计范围！' },
    coarseRatio: { defaultVal: 62.0, minValid: 50.0, maxValid: 75.0, desc: '粗集料比例（通常为 50%~75%）。', warningMsg: '粗集料配比超出常规！' },
    fineRatio: { defaultVal: 31.0, minValid: 20.0, maxValid: 40.0, desc: '细集料比例（通常为 20%~40%）。', warningMsg: '细集料配比超出常规！' },
    powderRatio: { defaultVal: 3.0, minValid: 1.5, maxValid: 6.0, desc: '矿粉比例（通常为 1.5%~6.0%）。', warningMsg: '矿粉配比超出常规！' },
  },
  'LM-PRIME': {
    lossRate: { defaultVal: 3.0, minValid: 1.0, maxValid: 5.0, desc: '透层油洒布洒漏损耗率经验值为 1.0%~5.0%。', warningMsg: '洒布损耗率超出常理(1%~5%)！' },
    managementRate: { defaultVal: 3.0, minValid: 1.0, maxValid: 10.0, desc: '通常为 1.0%~10.0%。', warningMsg: '费率偏离常规！' },
    profitRate: { defaultVal: 4.0, minValid: 1.0, maxValid: 12.0, desc: '通常为 1.0%~12.0%。', warningMsg: '费率偏离常规！' },
    taxRate: { defaultVal: 9.0, minValid: 3.0, maxValid: 9.0, desc: '标准税率 9% 或 3%。', warningMsg: '税率异常！' },
    tackApplicationRate: { defaultVal: 0.0012, minValid: 0.0008, maxValid: 0.0018, desc: '透层油洒布量规范要求通常在 0.0008~0.0018 t/m² (即 0.8~1.8 kg/m²)。', warningMsg: '洒布油量超出规范限制(0.8~1.8 kg/m²)！' },
    sprayProductivity: { defaultVal: 2500, minValid: 1800, maxValid: 3500, desc: '透层油洒布车日均洒布面积经验值为 1800~3500 m²/台班。', warningMsg: '洒布车工效异常！' },
  },
  'LM-BASE-CSM': {
    thicknessCm: { defaultVal: 20.0, minValid: 15.0, maxValid: 25.0, desc: '水泥稳定碎石基层设计厚度通常在 15~25cm。', warningMsg: '基层厚度异常！' },
    density: { defaultVal: 2.30, minValid: 2.15, maxValid: 2.40, desc: '水稳碎石干压实密度通常在 2.15~2.40 t/m³ 之间。', warningMsg: '水稳密度超出规范！' },
    lossRate: { defaultVal: 3.0, minValid: 1.5, maxValid: 5.0, desc: '水稳材料拌合施工损耗率通常为 1.5%~5.0%。', warningMsg: '损耗率设定偏高！' },
    haulDistanceKm: { defaultVal: 10.0, minValid: 2.0, maxValid: 30.0, desc: '基层水稳混合料合理运距 2~30km。', warningMsg: '运距超出合理范围！' },
    managementRate: { defaultVal: 4.0, minValid: 2.0, maxValid: 8.0, desc: '基层企业管理费率通常为 2.0%~8.0%。', warningMsg: '管理费率超出常规！' },
    profitRate: { defaultVal: 5.0, minValid: 2.0, maxValid: 10.0, desc: '测算利润计取率通常为 2.0%~10.0%。', warningMsg: '利润率超出常规！' },
    taxRate: { defaultVal: 9.0, minValid: 3.0, maxValid: 9.0, desc: '标准增值税率 9% 或 3%。', warningMsg: '税率异常！' },
    laborProductivity: { defaultVal: 120, minValid: 90, maxValid: 150, desc: '水稳基层人工工效一般为 90~150 m²/工日。', warningMsg: '人工工效偏离合理区间！' },
    paverProductivity: { defaultVal: 1500, minValid: 1000, maxValid: 1800, desc: '水稳专用摊铺机台班工效一般为 1000~1800 m²/台班。', warningMsg: '摊铺机工效偏离合理区间！' },
    rollerProductivity: { defaultVal: 1400, minValid: 900, maxValid: 1700, desc: '大吨位压路机组合联合台班工效一般为 900~1700 m²/台班。', warningMsg: '压路机工效偏离合理区间！' },
    asphaltRatio: { defaultVal: 5.0, minValid: 3.5, maxValid: 6.5, desc: '水泥设计剂量（通常为 3.5%~6.5%，过高易产生收缩开裂）。', warningMsg: '水泥剂量配比超出设计范围！' },
    coarseRatio: { defaultVal: 65.0, minValid: 50.0, maxValid: 75.0, desc: '粗集料级配比例（通常为 50%~75%）。', warningMsg: '粗集料比例异常！' },
    fineRatio: { defaultVal: 30.0, minValid: 20.0, maxValid: 45.0, desc: '细砂及石屑级配比例（通常为 20%~45%）。', warningMsg: '细集料比例异常！' },
    powderRatio: { defaultVal: 0.0, minValid: 0.0, maxValid: 5.0, desc: '一般水稳不加或极少加矿粉。', warningMsg: '矿粉配比不建议过高！' },
  },
}

export const SEED_RESOURCE_ITEMS: Omit<PriceResourceItem, 'quotes'>[] = [
  { id: 'R-LABOR-铺工', category: 'labor', name: '摊铺配合人工', spec: '配合摊铺辅助工', unit: '工日' },
  { id: 'R-LABOR-放样', category: 'labor', name: '测量放样工', spec: '路面高程及中心线测量', unit: '工日' },
  { id: 'R-MAT-沥青', category: 'material', name: '70# 道路石油沥青', spec: 'A级', unit: 't' },
  { id: 'R-MAT-粗集料', category: 'material', name: '粗集料', spec: '10-20mm 碎石', unit: 't' },
  { id: 'R-MAT-细集料', category: 'material', name: '细集料', spec: '机制砂/石屑 0-5mm', unit: 't' },
  { id: 'R-MAT-矿粉', category: 'material', name: '矿粉', spec: '石灰岩矿粉', unit: 't' },
  { id: 'R-MAT-水泥', category: 'material', name: 'P.O 42.5 水泥', spec: '散装普通硅酸盐水泥', unit: 't' },
  { id: 'R-FIN-AC20C', category: 'finished', name: 'AC-20C 沥青混合料', spec: '成品料', unit: 't' },
  { id: 'R-FIN-AC13C', category: 'finished', name: 'AC-13C 沥青混合料', spec: '成品料', unit: 't' },
  { id: 'R-FIN-SMA13', category: 'finished', name: 'SMA-13 沥青玛蹄脂碎石混合料', spec: '成品料', unit: 't' },
  { id: 'R-FIN-AC25C', category: 'finished', name: 'AC-25C 沥青混合料', spec: '成品料', unit: 't' },
  { id: 'R-FIN-BASE-CSM', category: 'finished', name: '水泥稳定碎石混合料', spec: '成品料', unit: 't' },
  { id: 'R-TRANS-混合料', category: 'transport', name: '成品沥青混合料运输', spec: '自卸车/保温运输', unit: 't·km' },
  { id: 'R-MACH-摊铺机', category: 'machine', name: '沥青摊铺机', spec: '9m 宽中大型摊铺机', unit: '台班' },
  { id: 'R-MACH-双钢轮', category: 'machine', name: '双钢轮压路机', spec: '13t 自行式双驱双振', unit: '台班' },
  { id: 'R-MACH-胶轮', category: 'machine', name: '胶轮压路机', spec: '26t 轮胎压路机', unit: '台班' },
  { id: 'R-MAT-木纤维', category: 'material', name: '路用木质素纤维', spec: '颗粒状/絮状', unit: 't' },
  { id: 'R-MAT-橡胶粉', category: 'material', name: '废胎改性橡胶粉', spec: '40目/路面改性级', unit: 't' },
]

export interface SeedQuote {
  id: string
  resourceId: string
  supplier: string
  price: number
  taxCaliber: string
  deliveryPoint: string
  collectedAt: string
  remark: string
}

export const SEED_QUOTES: SeedQuote[] = [
  { id: 'Q-L1-1', resourceId: 'R-LABOR-铺工', supplier: '中原路桥劳务公司', price: 260, taxCaliber: '含税', deliveryPoint: '项目所在地', collectedAt: '2026-06-01', remark: '含劳保及意外险' },
  { id: 'Q-L1-2', resourceId: 'R-LABOR-铺工', supplier: '八达建筑劳务派遣', price: 280, taxCaliber: '含税', deliveryPoint: '广东省内', collectedAt: '2026-05-15', remark: '熟练沥青操作配合工' },
  { id: 'Q-L2-1', resourceId: 'R-LABOR-放样', supplier: '项目部内部测算', price: 300, taxCaliber: '内部分摊', deliveryPoint: '项目所在地', collectedAt: '2026-06-01', remark: '不计外包利润' },
  { id: 'Q-L2-2', resourceId: 'R-LABOR-放样', supplier: '联友专业测绘工作室', price: 320, taxCaliber: '专票到场价', deliveryPoint: '项目所在地', collectedAt: '2026-04-10', remark: '含高精度测绘仪租赁' },
  { id: 'Q-M1-1', resourceId: 'R-MAT-沥青', supplier: '中石化南方分公司', price: 4200, taxCaliber: '含税到场', deliveryPoint: '沥青拌合站', collectedAt: '2026-06-01', remark: '大客户合同价' },
  { id: 'Q-M1-2', resourceId: 'R-MAT-沥青', supplier: '建安路桥物资商贸', price: 4150, taxCaliber: '含税到场', deliveryPoint: '广州东仓自提', collectedAt: '2026-05-28', remark: '运距需另计' },
  { id: 'Q-M1-3', resourceId: 'R-MAT-沥青', supplier: '历史采购平均参考价', price: 4000, taxCaliber: '不含税到场', deliveryPoint: '沥青拌合站', collectedAt: '2025-11-20', remark: '历史项目估算' },
  { id: 'Q-M2-1', resourceId: 'R-MAT-粗集料', supplier: '顺达联营石料厂', price: 95, taxCaliber: '含税到场', deliveryPoint: '拌合站料仓', collectedAt: '2026-05-28', remark: '石质硬度优，级配稳定' },
  { id: 'Q-M2-2', resourceId: 'R-MAT-粗集料', supplier: '广泰建材石场', price: 98, taxCaliber: '含税到场', deliveryPoint: '拌合站料仓', collectedAt: '2026-06-02', remark: '距离较近，保障供应' },
  { id: 'Q-M3-1', resourceId: 'R-MAT-细集料', supplier: '顺达联营石料厂', price: 90, taxCaliber: '含税到场', deliveryPoint: '拌合站料仓', collectedAt: '2026-05-28', remark: '含水率控制优' },
  { id: 'Q-M3-2', resourceId: 'R-MAT-细集料', supplier: '信步河砂物资站', price: 110, taxCaliber: '含税到场', deliveryPoint: '拌合站料仓', collectedAt: '2026-06-01', remark: '天然河砂，含泥量低' },
  { id: 'Q-M4-1', resourceId: 'R-MAT-矿粉', supplier: '益鑫建材矿粉厂', price: 260, taxCaliber: '含税到场', deliveryPoint: '拌合站罐仓', collectedAt: '2026-06-01', remark: '目数符合路面施工规范' },
  { id: 'Q-M4-2', resourceId: 'R-MAT-矿粉', supplier: '华润水泥代理商', price: 280, taxCaliber: '含税到场', deliveryPoint: '拌合站罐仓', collectedAt: '2026-05-18', remark: '常备货源充足' },
  { id: 'Q-CEM-1', resourceId: 'R-MAT-水泥', supplier: '海螺水泥集团分公司', price: 420, taxCaliber: '含税到场', deliveryPoint: '项目所在地料仓', collectedAt: '2026-06-01', remark: '大客户直供合作价' },
  { id: 'Q-CEM-2', resourceId: 'R-MAT-水泥', supplier: '南方水泥建材商贸', price: 440, taxCaliber: '含税到场', deliveryPoint: '项目所在地', collectedAt: '2026-05-20', remark: '' },
  { id: 'Q-FIN-AC20C-D', resourceId: 'R-FIN-AC20C', supplier: '昆明晋宁沥青拌合站', price: 520, taxCaliber: '含税到场', deliveryPoint: '项目卸料点', collectedAt: '2026-06-15', remark: '成品到场价，含拌合与常规运输' },
  { id: 'Q-FIN-AC20C-F', resourceId: 'R-FIN-AC20C', supplier: '昆明晋宁沥青拌合站', price: 490, taxCaliber: '含税出厂', deliveryPoint: '拌合站自提', collectedAt: '2026-06-15', remark: '成品出厂价，不含项目运输' },
  { id: 'Q-FIN-AC13C-D', resourceId: 'R-FIN-AC13C', supplier: '昆明晋宁沥青拌合站', price: 540, taxCaliber: '含税到场', deliveryPoint: '项目卸料点', collectedAt: '2026-06-15', remark: '成品到场价，含拌合与常规运输' },
  { id: 'Q-FIN-AC13C-F', resourceId: 'R-FIN-AC13C', supplier: '昆明晋宁沥青拌合站', price: 510, taxCaliber: '含税出厂', deliveryPoint: '拌合站自提', collectedAt: '2026-06-15', remark: '成品出厂价，不含项目运输' },
  { id: 'Q-FIN-SMA13-D', resourceId: 'R-FIN-SMA13', supplier: '云南高等级路面材料站', price: 650, taxCaliber: '含税到场', deliveryPoint: '项目卸料点', collectedAt: '2026-06-15', remark: 'SMA成品到场价，含改性料加工与常规运输' },
  { id: 'Q-FIN-SMA13-F', resourceId: 'R-FIN-SMA13', supplier: '云南高等级路面材料站', price: 620, taxCaliber: '含税出厂', deliveryPoint: '拌合站自提', collectedAt: '2026-06-15', remark: 'SMA成品出厂价，不含项目运输' },
  { id: 'Q-FIN-AC25C-D', resourceId: 'R-FIN-AC25C', supplier: '昆明晋宁沥青拌合站', price: 500, taxCaliber: '含税到场', deliveryPoint: '项目卸料点', collectedAt: '2026-06-15', remark: '成品到场价，含拌合与常规运输' },
  { id: 'Q-FIN-AC25C-F', resourceId: 'R-FIN-AC25C', supplier: '昆明晋宁沥青拌合站', price: 470, taxCaliber: '含税出厂', deliveryPoint: '拌合站自提', collectedAt: '2026-06-15', remark: '成品出厂价，不含项目运输' },
  { id: 'Q-FIN-CSM-D', resourceId: 'R-FIN-BASE-CSM', supplier: '昆明水稳拌合站', price: 135, taxCaliber: '含税到场', deliveryPoint: '项目卸料点', collectedAt: '2026-06-15', remark: '水稳成品到场价，含集中拌合与常规运输' },
  { id: 'Q-FIN-CSM-F', resourceId: 'R-FIN-BASE-CSM', supplier: '昆明水稳拌合站', price: 120, taxCaliber: '含税出厂', deliveryPoint: '拌合站自提', collectedAt: '2026-06-15', remark: '水稳成品出厂价，不含项目运输' },
  { id: 'Q-T1-1', resourceId: 'R-TRANS-混合料', supplier: '宏运联营车队', price: 1.55, taxCaliber: '含税', deliveryPoint: '项目卸料点', collectedAt: '2026-06-01', remark: '按吨公里计价，含装等待' },
  { id: 'Q-T1-2', resourceId: 'R-TRANS-混合料', supplier: '佳通运输服务有限公司', price: 1.65, taxCaliber: '含税', deliveryPoint: '项目卸料点', collectedAt: '2026-06-01', remark: '保温自卸车，防离析性能佳' },
  { id: 'Q-T1-3', resourceId: 'R-TRANS-混合料', supplier: '旧项目结算均价', price: 1.48, taxCaliber: '不含税', deliveryPoint: '项目卸料点', collectedAt: '2026-04-15', remark: '历史项目结算核算价' },
  { id: 'Q-MA1-1', resourceId: 'R-MACH-摊铺机', supplier: '捷力路面机械租赁厂', price: 5600, taxCaliber: '不含燃油，含操作手', deliveryPoint: '工地现场', collectedAt: '2026-06-01', remark: '进出场费另计' },
  { id: 'Q-MA1-2', resourceId: 'R-MACH-摊铺机', supplier: '中铁装备设备租赁部', price: 5800, taxCaliber: '不含燃油，含操作手', deliveryPoint: '工地现场', collectedAt: '2026-05-10', remark: '含操作手加班费' },
  { id: 'Q-MA2-1', resourceId: 'R-MACH-双钢轮', supplier: '捷力路面机械租赁厂', price: 1800, taxCaliber: '不含燃油，含操作手', deliveryPoint: '工地现场', collectedAt: '2026-06-01', remark: '' },
  { id: 'Q-MA2-2', resourceId: 'R-MACH-双钢轮', supplier: '顺安工程设备租赁公司', price: 1700, taxCaliber: '不含燃油，含操作手', deliveryPoint: '工地现场', collectedAt: '2026-05-20', remark: '' },
  { id: 'Q-MA3-1', resourceId: 'R-MACH-胶轮', supplier: '捷力路面机械租赁厂', price: 2100, taxCaliber: '不含燃油，含操作手', deliveryPoint: '工地现场', collectedAt: '2026-06-01', remark: '' },
  { id: 'Q-MA3-2', resourceId: 'R-MACH-胶轮', supplier: '顺安工程设备租赁公司', price: 2000, taxCaliber: '不含燃油，含操作手', deliveryPoint: '工地现场', collectedAt: '2026-05-20', remark: '' },
  // 云南省昆明及周边地区参考市场价与信息价 (2026年6月)
  { id: 'Q-L1-YN', resourceId: 'R-LABOR-铺工', supplier: '云南本地路桥劳务队', price: 230, taxCaliber: '含税', deliveryPoint: '昆明及周边项目', collectedAt: '2026-06-15', remark: '配合摊铺辅助工，云南本地劳务行情' },
  { id: 'Q-L2-YN', resourceId: 'R-LABOR-放样', supplier: '昆明精测路桥工作室', price: 300, taxCaliber: '专票到场价', deliveryPoint: '云南省内项目', collectedAt: '2026-06-15', remark: '测量放样技工，含仪器租赁分摊' },
  { id: 'Q-M1-YN', resourceId: 'R-MAT-沥青', supplier: '云路物资供应站', price: 4600, taxCaliber: '含税到场', deliveryPoint: '昆明晋宁拌合站', collectedAt: '2026-06-12', remark: '70#道路石油沥青A级，结合运费与炼厂报价' },
  { id: 'Q-M2-YN', resourceId: 'R-MAT-粗集料', supplier: '昆明安宁联营石料厂', price: 92, taxCaliber: '含税到场', deliveryPoint: '昆明周边拌合站', collectedAt: '2026-06-10', remark: '10-20mm碎石，石质坚硬，级配优良' },
  { id: 'Q-M3-YN', resourceId: 'R-MAT-细集料', supplier: '宜良砂石骨料基地', price: 88, taxCaliber: '含税到场', deliveryPoint: '昆明周边拌合站', collectedAt: '2026-06-10', remark: '机制砂/石屑 0-5mm，符合路面机制砂标准' },
  { id: 'Q-M4-YN', resourceId: 'R-MAT-矿粉', supplier: '呈贡新材料矿粉厂', price: 300, taxCaliber: '含税到场', deliveryPoint: '拌合站罐仓', collectedAt: '2026-06-11', remark: '石灰岩矿粉，目数符合路面规范' },
  { id: 'Q-CEM-YN', resourceId: 'R-MAT-水泥', supplier: '昆明红狮水泥直供站', price: 440, taxCaliber: '含税到场', deliveryPoint: '项目所在地料仓', collectedAt: '2026-06-15', remark: 'P.O 42.5 散装普通硅酸盐水泥' },
  { id: 'Q-T1-YN', resourceId: 'R-TRANS-混合料', supplier: '云南畅达路运车队', price: 1.40, taxCaliber: '含税', deliveryPoint: '云南省内项目', collectedAt: '2026-06-15', remark: '自卸保温车运输成品沥青混合料' },
  { id: 'Q-MA1-YN', resourceId: 'R-MACH-摊铺机', supplier: '昆明徐工机械租赁商', price: 1600, taxCaliber: '不含燃油，含操作手', deliveryPoint: '工地现场', collectedAt: '2026-06-12', remark: '9m摊铺机，日租台班费' },
  { id: 'Q-MA2-YN', resourceId: 'R-MACH-双钢轮', supplier: '昆明路友设备租赁公司', price: 1350, taxCaliber: '不含燃油，含操作手', deliveryPoint: '工地现场', collectedAt: '2026-06-12', remark: '13t双钢轮压路机，台班租赁' },
  { id: 'Q-MA3-YN', resourceId: 'R-MACH-胶轮', supplier: '昆明路友设备租赁公司', price: 1450, taxCaliber: '不含燃油，含操作手', deliveryPoint: '工地现场', collectedAt: '2026-06-12', remark: '26t胶轮压路机，台班租赁' },
  // 沥青混合料添加剂
  { id: 'Q-M5-1', resourceId: 'R-MAT-木纤维', supplier: '廊坊百奥纤维制品厂', price: 3200, taxCaliber: '含税到场', deliveryPoint: '混合料搅拌站', collectedAt: '2026-05-15', remark: '外省运输，到场价格' },
  { id: 'Q-M5-YN', resourceId: 'R-MAT-木纤维', supplier: '昆明万路交通材料工程公司', price: 3500, taxCaliber: '含税到场', deliveryPoint: '昆明晋宁拌合站', collectedAt: '2026-06-15', remark: 'SMA路面上面层添加材料' },
  { id: 'Q-M6-1', resourceId: 'R-MAT-橡胶粉', supplier: '常州再生橡胶有限公司', price: 2300, taxCaliber: '含税到场', deliveryPoint: '混合料搅拌站', collectedAt: '2026-05-15', remark: '外省调拨' },
  { id: 'Q-M6-YN', resourceId: 'R-MAT-橡胶粉', supplier: '云南西双版纳再生橡胶加工厂', price: 2600, taxCaliber: '含税到场', deliveryPoint: '昆明周边拌合站', collectedAt: '2026-06-15', remark: '本地货源，改性沥青添加级' },
]

export const SEED_SELECTED_QUOTES: Record<string, string> = {
  'R-LABOR-铺工': 'Q-L1-1',
  'R-LABOR-放样': 'Q-L2-1',
  'R-MAT-沥青': 'Q-M1-1',
  'R-MAT-粗集料': 'Q-M2-1',
  'R-MAT-细集料': 'Q-M3-1',
  'R-MAT-矿粉': 'Q-M4-1',
  'R-MAT-水泥': 'Q-CEM-1',
  'R-FIN-AC20C': 'Q-FIN-AC20C-D',
  'R-FIN-AC13C': 'Q-FIN-AC13C-D',
  'R-FIN-SMA13': 'Q-FIN-SMA13-D',
  'R-FIN-AC25C': 'Q-FIN-AC25C-D',
  'R-FIN-BASE-CSM': 'Q-FIN-CSM-D',
  'R-TRANS-混合料': 'Q-T1-1',
  'R-MACH-摊铺机': 'Q-MA1-1',
  'R-MACH-双钢轮': 'Q-MA2-1',
  'R-MACH-胶轮': 'Q-MA3-1',
  'R-MAT-木纤维': 'Q-M5-YN',
  'R-MAT-橡胶粉': 'Q-M6-YN',
}
